include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'



build:
  stage: build
  tags:
    - build
  artifacts:
    paths:
      - build
  script:
    - git submodule update --init --recursive && mkdir build && cd build && CXX=g++-10 cmake -DCMAKE_BUILD_TYPE=Release .. && make
  only:
    - master
    - merge_requests

test:
  stage: test
  tags:
    - build
  script:
    - ./build/tests/Tests_run --gtest_output="xml:report.xml"
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
  only:
    - master
    - merge_requests
